### ISSUE TITLE
Complete Code for the Android Application is Needed.

### ISSUE THREAD

**Issue by devdattaT** [dasaki/android_fft_minim#1]
I was trying to use the given FFT classes in my Android app, but couldn't figure out how to get it working. So I tried to install the given APK file. It did install, but I couldn't run the app. It always crashed. 

Log cat had the following error: 
`java.io.FileNotFoundException: /proc/mtprof/status: open failed: ENOENT (No such file or directory)`

If the complete android code was available, then it would helpful to understand how to use the classes, or debug the error in the app.

**Comment by dasaki** [comment]
Complete code is included (3 files): 

android_fft_minim.pde
FFT.java
FourierTransform.java

Tested and built with Processing 2.0b8 (android mode). Processing loads automatically all the code files that are located in the same folder as the .pde sketch.
