### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by uraltermann** [dasaki/android_fft_minim#2]
I'm trying to run your code on my android device, but it results in an error that says:
java.ioFileNotFoundExeption: /data/data/com.calsignlabs.apde/app_build/bin/android_fft_minim.apk.res does not exist. what kind of file is that? how can i find it? any suggestions?
Thanks!

**Comment by dasaki** [comment]
Are you trying the apk?
It is quite old and might not work in newer Android versions.
If so, can you please try to use the APDE app, as explained in the last
edit of the post (March 13th 2015)?
Regards

**Comment by uraltermann** [comment]
I'm using the APDE app on lollipop (5.0) but I just found out, that the problem exists not just with this sketch. Already tried to reinstall, but doesn't help.

**Comment by dasaki** [comment]
I just run the sketch without issues, even after upgrading to Android 5.1
Did you store all the files (.pde, .java, etc) ditectly in a folder called
"android_fft_minim", inside the Sketchbook folder (mine is:
storage/sdcard0/Sketchbook) ?

**Comment by uraltermann** [comment]
I downgraded my phone to android 4.4.4 and it's working fine
might be some sony specific problem with their version of lollypop

**Comment by dasaki** [comment]
So shall the issue be closed?
